### ISSUE TITLE
Offset Cubemap

### ISSUE THREAD

**Issue by telganainy** [facebook/transform360#23]
Hi,

Regarding the latest update to the code. I was wondering what is the "LAYOUT_CUBEMAP_23_OFFCENTER" layout? is it supposed to be the offset cubemap? as I can't quite visualize it's output. And if not, is there plans that you'll release some documentation/code on the implementation details of the offset cubemap? Also, I noticed you have in the code "LAYOUT_FB", but no more details about it.

Thanks so much

**Comment by telganainy** [comment]
Hi,

Any updates on the offset cubemap? Code or documentation?

Thanks so much.

**Comment by puffpio** [comment]
LAYOUT_CUBEMAP_23_OFFCENTER has two things different compared to the standard cubemap
1) the cube face layout, instead of 3 x 2 cubes, its 2 x 3 cubes (we wanted to pack stereo video Side By Side so 2 x 3 stayed within some bounds of horizontal resolution)
2) the actual cube face order and orientation are different. It uses something called a baseball cover layout where we try to keep shared edges together to minimize sharp edge transitions. For example, we keep Left-Center-Right together so it looks like one continuous long strip

You can then apply the offset/offcenter parameter to adjust the offset strength, see Cass Everitt's talk at Oculus Connect 3 (its on the Oculus channel on Youtube) for a pretty good explanation of how it works.

Thanks

**Comment by telganainy** [comment]
Thanks so much. Now it's clear.

**Comment by mikeswanson** [comment]
Did anyone ever find Cass Everitt's talk? I looked through the [sessions](https://www.youtube.com/playlist?list=PLL2xVXGs1SP7RjXUBwur43flR7tRcbYLD), but I couldn't find anywhere that he is presenting.

**Comment by HazemSamir** [comment]
Hey, @mikeswanson I found [his talk](https://www.youtube.com/watch?v=uSHTsGNFmeM&index=7&list=PLL2xVXGs1SP7RjXUBwur43flR7tRcbYLD) in the playlist. There are two presenters Cass and James. Cass starts talking about different projections around minute 14.

hope it helps :)

**Comment by mikeswanson** [comment]
Thank you! Of course, I hadn't looked at the Mobile SDK session. :-)

**Comment by bnussey** [comment]
Here's the link for anyone else - https://youtu.be/uSHTsGNFmeM
