### ISSUE TITLE
I find a bug:the edge between front frace and right face is error

### ISSUE THREAD

**Issue by xuws20** [facebook/transform360#38]
I compile transform360 in visual studio 2015,get the front face and right face as follows:
http://a3.qpic.cn/psb?/V11uORQl30DIq5/xjQHrSUVyvfNgqSTOqnyI3JJuWG0UbMvwFuBfy.cHVk!/b/dEQAAAAAAAAA&bo=BQQcAgAAAAADADo!&rf=viewer_4
![figure_1](https://user-images.githubusercontent.com/13374932/29703214-31c9c67e-89a7-11e7-9462-9b73ed59c1f2.png)

**Comment by xuws20** [comment]
[http://a3.qpic.cn/psb?/V11uORQl30DIq5/xjQHrSUVyvfNgqSTOqnyI3JJuWG0UbMvwFuBfy.cHVk!/b/dEQAAAAAAAAA&bo=BQQcAgAAAAADADo!&rf=viewer_4](url)

**Comment by xuws20** [comment]
http://qpic.cn/g0foE6VoC

**Comment by xuws20** [comment]
http://a3.qpic.cn/psb?/V11uORQl30DIq5/xjQHrSUVyvfNgqSTOqnyI3JJuWG0UbMvwFuBfy.cHVk!/b/dEQAAAAAAAAA&bo=BQQcAgAAAAADADo!&rf=viewer_4

**Comment by evgenykuzyakov** [comment]
It's because of expansion coefficient. We expand each cube face by **expand_coef - 1** percentage. The default expansion coefficient is 1.01. Which is 101% of the plane cube face. We do this to avoid color bleeding during encoding with yuv420. You can set it to 1.00 to avoid expansion. This should resolve your edge issue.

**Comment by xuws20** [comment]
thanks
