### ISSUE TITLE
How can I build the support to generate cube faces with different resolution ?

### ISSUE THREAD

**Issue by harshil93** [facebook/transform360#52]
I am very new to this field and trying out various things to learn ?

I would like to generate cube faces in the output video with different resolutions to hack together an adaptive solution as described in the article for [transform360](https://code.facebook.com/posts/1126354007399553/next-generation-video-encoding-techniques-for-360-video-and-vr/)

I have the two ideas, and would like the feedback

1. Enhance the tranform360 library to take more options to support different resolution for each of the cubeface.

2. Use a filter which will change the resolution as per the inputs for each of the faces.

**Comment by kcircnc** [comment]
Actually you can use `[-filter_complex](https://ffmpeg.org/ffmpeg-filters.html#toc-Filtergraph-syntax-1)` option to combine transform360 with other native ffmpeg filters to achieve want you proposed without changing the transform360 code.

One thing to keep in mind though, is that the resolution difference between two faces will make the shared edge between the two faces VERY visible. This will affect viewing experience greatly. You can try out the `cubemap180` filter in transform_v1 to experience it yourself. cubemap180 is basically what you proposed, but instead of allowing the 6 faces have different resolutions, it divides the cube into two halves and allow the two to have different resolutions.

**Comment by JaiiRLopeZ** [comment]
@harshil93 Did you achieve to code the faces with different resolutions?
